version: '3.8'

services:
  cache-redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0.36
    container_name: mysql-cache
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./mysql-data-cache-redis:/var/lib/mysql
    env_file:
      - ./env/mysql.env

volumes:
  mysql-data-cache-redis: